apiVersion: v1
kind: Service
metadata:
  name: phoenix
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
  name: phoenix
spec:
  ports:
    - name: phoenix-ui
      protocol: TCP
      port: 6006
      targetPort: 6006
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
  type: ClusterIP